// ignore: unused_import, uri_does_not_exist
import 'package:future_solutions/di/injection.config.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

/// Global GetIt instance for dependency injection.
final getIt = GetIt.instance;

/// Initialize dependency injection.
///
/// Call this in main.dart before running the app.
/// The [injection.config.dart] file will be generated by build_runner
/// when you run: `flutter pub run build_runner build --delete-conflicting-outputs`
@InjectableInit(
  initializerName: 'init',
  preferRelativeImports: true,
  asExtension: false,
)
void configureDependencies() => init(getIt);
